// Generated by web/scripts/extract-config.mjs from the services' application.yml files and
// chaos/loadgen.py. Do not edit; run `npm run config` after changing the configuration.
export const CONFIG = {
  "inventoryBreaker": {
    "slidingWindowSize": 10,
    "minimumNumberOfCalls": 4,
    "failureRateThreshold": 50,
    "waitDurationInOpenStateMs": 5000,
    "permittedNumberOfCallsInHalfOpenState": 2
  },
  "inventoryTimeLimitMs": 800,
  "processorBreaker": {
    "slidingWindowSize": 20,
    "minimumNumberOfCalls": 10,
    "failureRateThreshold": 60,
    "waitDurationInOpenStateMs": 5000,
    "permittedNumberOfCallsInHalfOpenState": 3
  },
  "processorTimeLimitMs": 1000,
  "processorRetry": {
    "maxAttempts": 3,
    "waitDurationMs": 200
  },
  "payment": {
    "sweepMs": 1000,
    "sweepGraceMs": 3000,
    "retryDelayMs": 2000
  },
  "processor": {
    "limit": 10000,
    "transientPercent": 5,
    "slowPercent": 1,
    "slowMillis": 3000
  },
  "cacheTtlMs": 60000,
  "outboxPollMs": 200,
  "saga": {
    "reservationMs": 60000,
    "paymentMs": 120000,
    "maxRedrives": 1,
    "reaperMs": 5000
  },
  "dlq": {
    "maxAttempts": 8,
    "maxReplays": 3
  },
  "stockSeed": {
    "SKU-ALPHA": 100000,
    "SKU-BRAVO": 100000,
    "SKU-CHARLIE": 100000,
    "SKU-SCARCE": 40
  },
  "load": {
    "skus": [
      "SKU-ALPHA",
      "SKU-BRAVO",
      "SKU-CHARLIE",
      "SKU-SCARCE"
    ],
    "weights": [
      40,
      30,
      25,
      5
    ],
    "quantity": [
      1,
      3
    ],
    "unitPrice": [
      5,
      80
    ]
  }
} as const;
